services:
  nebula-sync:
    container_name: nebula-sync
    image: ghcr.io/lovelaze/nebula-sync:latest
    env_file: nebula-sync.env
    networks:
      macvlan_100:
        ipv4_address: 10.69.1.162
        mac_address: 6a:4d:45:fd:6d:80

networks:
  macvlan_100:
    name: macvlan_100
    external: true
  backend:
    name: backend#
    external: true